name: Build CompShop Application
on: push
jobs:
  build-project:
    name: Build project
    runs-on: ubuntu-latest
    steps:
      - name: Install pnpm
        run: curl -fsSL https://get.pnpm.io/install.sh | bash -
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Install PNPM dependencies
        run: pnpm install
      - name: Build project assets
        run: pnpm build